con2/kompassi

core/migrations/0003_auto_20150813_1907.py
core/models.py
labour/views/query_views.py

- Rough field validation,
- use fallback format when formatting date before computers.

core, labour: Add some sanity checking for person birth date.

---

membership/migrations/0014_term_payment_type.py
membership/models.py
membership/templates/membership_apply_view.jade

Atm there's only one payment type (direct bank transfer), but new types can now be added.

Admin can choose membership fee payment type

---

core/models.py
core/templates/base.jade
labour/constants.py
labour/helpers.py
labour/models.py
labour/templates/labour_admin_onboarding_view.jade
labour/urls.py
labour/views/__init__.py
labour/views/admin_views.py

Initial implementation of onboarding

---

events/ropecon2018/forms.py
events/ropecon2018/locale/fi/LC_MESSAGES/django.po
programme/models/programme.py

Our LARP team wanted some more translation fixes. These can be merged at your convenience.

More translation fixes

---

programme/models/programme.py

Add revolving door and short blurp to Ropecon program export.

Add revolving door and short blurp to Ropecon program export

---

events/ropecon2020/forms.py
events/ropecon2020/locale/fi/LC_MESSAGES/django.po
events/ropecon2020/management/commands/setup_ropecon2020.py

Added and changed some Ropecon 2020 rpg form things and also created translations to this form.

Ropecon2020 rpg fixes

---

events/finncon2023/management/commands/setup_finncon2023.py

Added new programme categories for Finncon2023, made old ones non-visible to public

Finncon 2023: New programme categories

---

backend/events/tracon2024/models.py

chore(Tracon2024): small labour form fix

---

backend/access/tests.py
backend/core/tests.py
backend/desuprofile_integration/tests.py
backend/labour/tests.py
backend/labour_common_qualifications/tests.py
backend/programme/tests.py

With https://github.com/akx/codemod-unittest-to-pytest-asserts/

chore: codemod unittest assertions

---

backend/access/models/access_organization_meta.py
backend/badges/views/badges_admin_create_view.py
backend/core/models/event.py
backend/membership/models.py

Via `vulture` and PyCharm's inspections.

chore: remove unreachable or redeclared code

---

.github/workflows/backend.yaml
.github/workflows/frontend.yaml

* version updates and removal of unnecessary bits and pieces
* fixing the frontend build to not attempt GHCR login & image push when there might be no credentials (I sure hope I got my Bash right)

ci: small renovations

---

backend/organizations/kotae_ry/management/commands/setup_kotae_ry.py

Setup membership applications for Kotae ry. Update Kotae ry organization description.

chore(kotaery): setup membership applications

---

backend/events/frostbite2024/management/commands/setup_frostbite2024.py
backend/forms/excel_export.py
backend/forms/graphql/mutations/init_file_upload.py
backend/forms/graphql/response.py
backend/forms/models/field.py
backend/forms/models/response.py
backend/forms/tests.py
backend/forms/utils/process_form_data.py
backend/forms/utils/s3_presign.py
backend/forms/utils/summarize_responses.py
frontend/src/app/[locale]/events/[eventSlug]/programs/new/[formSlug]/page.tsx
frontend/src/app/[locale]/events/[eventSlug]/surveys/[surveySlug]/actions.ts
frontend/src/app/[locale]/events/[eventSlug]/surveys/[surveySlug]/page.tsx
frontend/src/app/[locale]/events/[eventSlug]/surveys/[surveySlug]/responses/[responseId]/page.tsx
frontend/src/app/[locale]/events/[eventSlug]/surveys/[surveySlug]/responses/page.tsx
frontend/src/app/[locale]/events/[eventSlug]/surveys/[surveySlug]/responses/summary/FieldSummaryComponent.tsx
frontend/src/app/[locale]/events/[eventSlug]/surveys/[surveySlug]/responses/summary/FileUploadFieldSummaryComponent.tsx
frontend/src/app/[locale]/profile/responses/[responseId]/page.tsx
frontend/src/components/SchemaForm/SchemaFormInput.tsx
frontend/src/components/SchemaForm/SchemaFormResponse.tsx
frontend/src/components/SchemaForm/UploadedFileCards.tsx
frontend/src/components/SchemaForm/index.tsx
frontend/src/components/SchemaForm/models.ts
frontend/src/translations/en.tsx
frontend/src/translations/fi.tsx

Show file uploads in single response view, response list and summary

---

backend/kompassi/settings.py

https://github.com/w3c/webappsec-csp/issues/8

Fix redirect to Kompassi V2 after login

---

backend/events/frostbite2024/forms/number-field-test.yml
backend/events/frostbite2024/management/commands/setup_frostbite2024.py
backend/events/tracon2024/forms/expense-claim-fi.yml
backend/forms/models/field.py
backend/forms/tests.py
backend/forms/utils/process_form_data.py
frontend/src/components/SchemaForm/SchemaFormInput.tsx
frontend/src/components/SchemaForm/models.ts

Implement NumberField and DecimalField

---

backend/events/tracon2024/forms/artisan-application-dimensions.yml
backend/events/tracon2024/forms/artisan-application-en.yml
backend/events/tracon2024/forms/artisan-application-fi.yml
backend/events/tracon2024/management/commands/setup_tracon2024.py
backend/forms/admin.py

Tracon 2024 artisan application/signup.
EN/FI forms and dimensions.
Also adds Survey's key_fields to django admin.

Tracon 2024 artisan application

---

backend/events/matsucon2024/forms/artist-alley-application-en.yml
backend/events/matsucon2024/forms/artist-alley-application-fi.yml

Front shows an error when rendering form. Fix some html links and slugs.

chore(matsucon2024): fix application form html links

---

backend/events/tracon2024/forms/vendor-application-en.yml
backend/events/tracon2024/forms/vendor-application-fi.yml

Tracon 2024 myyjähaun lomakkeet

---

backend/kubernetes/production.vars.yaml

Add `*.solmukohta.eu` to `csp_allowed_login_redirects`

Add *.solmukohta.eu to csp_allowed_login_redirects

---

backend/events/matsucon2024/forms.py

Took away the need for lodging.

chore(matsucon2024): Disable lodging option in org application form

---

backend/tickets/views/tickets_admin_export_yearly_statistics_view.py

Fix date calculation after days_to_event was changed to be negative numbers

fix(tickets): fix date calculation for non-sales dates in sales statistics csv

---

backend/tickets/views/tickets_admin_export_yearly_statistics_view.py

Omit data for future dates in sales statistics csv export.
The sales amounts are just 0 and cumulative values stay static, they don't contain any useful info.
Graph series lines are better off with ending in today.

fix(tickets): omit data for future dates in sales statistics csv

---

backend/program_v2/importers/ropecon2024.py

Add accessilibity dimension and map values

chore(ropecon2024): Accessibility dimension

---

backend/program_v2/importers/ropecon2024.py

Dimensions: Tardet audience and langauge
Topic: (yearly) theme

chore(ropecon2024): Target audience, language, yearly theme

---

backend/emprinten/files.py
backend/emprinten/renderer.py
backend/emprinten/utils.py
backend/emprinten/var_help.py
backend/labour/views/public_views.py

Cherry-pickable:
- Improve error handling during csv processing.
- Add birthdate value into data supplied for work certificate template. (Requires template update for it to actually appear.)

feat(emprinten): Errors and birthdate

---

backend/programme/models/paikkala_data/kulttuurikeskus-stoa/paasali.csv

Individual seats this time so it doesn't crash

Add Paikkala data for Stoa Pääsali

---

backend/events/tracon2025/forms/car-usage-dimensions.yml
backend/events/tracon2025/forms/car-usage-en.yml
backend/events/tracon2025/forms/car-usage-fi.yml
backend/events/tracon2025/forms/expense-claim-dimensions.yml
backend/events/tracon2025/forms/expense-claim-en.yml
backend/events/tracon2025/forms/expense-claim-fi.yml
backend/events/tracon2025/management/commands/setup_tracon2025.py

Few weeks time for thoughts, to be merged before year ends.
This time I would like to try to have km-expenses and others on separate forms instead of all in one.

chore(tracon2025): add expense request forms

---

backend/events/cosmocon2025/management/commands/setup_cosmocon2025.py
backend/kompassi/settings.py
backend/organizations/cosmocon_ry/apps.py
backend/organizations/cosmocon_ry/management/commands/setup_cosmocon_ry.py

Coscomon 2025 lipunmyynti käyttäen tickets v2.
Huom. setup-skriptissä myös setup_tickets jota ei käytetä.

chore(cosmocon2025): ticket sales

---

backend/events/matsucon2025/management/commands/setup_matsucon2025.py
backend/kompassi/settings.py

To test locally: `docker compose up`, then navigate to `http://localhost:3000/matsucon2025/products` and log in as `mahti:mahti`.

chore(matsucon2025): setup core and tickets v2
